### ISSUE TITLE
Remove unused functions

### ISSUE THREAD

**Issue by kallewesterling** [zackxconti/bnmetamodel_gh#23]
`alphanum_key`, `len_csvdata`, `kfoldToList` are unused functions in the Helper_functions.py file. (`ranges`, `draw_barchartpd`, `draw_histograms` are other functions not currently used, but still in the commented-out code)

## Suggested solution

Remove unused functions.

## Related issues

- [x] #22

**Comment by ghubrakesh** [comment]
Are you sure all the functions you mentioned above are not used in the code? If they are used, removing them might cause errors in the code.
Please confirm, so I can proceed to work on it.

**Comment by kallewesterling** [comment]
Thank you so much for engaging @ghubrakesh. We'd love to have your help soon. We're only just now starting to work on this package, and opening it up for open-source contribution. Unfortunately, the codebase is still too fragile and we need to first establish a workflow where we know which issues to tackle first. If you'd like, I'll make sure to stay in touch with you here when we'd love to see your contribution to the codebase.

**Comment by kallewesterling** [comment]
Adding more marking of functions, ready for review in this issue:
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BN_Metamodel_easy.py#L39
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BN_Metamodel_easy.py#L43
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BN_Metamodel_easy.py#L47
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BN_Metamodel_easy.py#L51C11-L51C11
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BN_Metamodel_easy.py#L57
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BN_Metamodel_easy.py#L63C1-L63C1
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BayesianNetwork.py#L76
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BayesianNetwork.py#L86
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BayesianNetwork.py#L144
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BayesianNetwork.py#L321
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BayesianNetwork.py#L507
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BayesianNetwork.py#L593
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BayesianNetwork.py#L688
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/BayesianNetwork.py#L908
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/Helper_functions.py#L30
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/Helper_functions.py#L40
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/Helper_functions.py#L47
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/Helper_functions.py#L86
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/Helper_functions.py#L136
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/Helper_functions.py#L162
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/Helper_functions.py#L215
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/Helper_functions.py#L271
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/Helper_functions.py#L541
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/Helper_functions.py#L554
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/Helper_functions.py#L575
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/other_functions.py#L11
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/other_functions.py#L17
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/other_functions.py#L36
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/other_functions.py#L67
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/other_functions.py#L95
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/other_functions.py#L164
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/other_functions.py#L191
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/other_functions.py#L214
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/other_functions.py#L282
- [ ] https://github.com/zackxconti/bnmetamodel_gh/blob/44241c7b10a4522b43ee148fc59439b264ac11fd/bnmetamodel_gh/other_functions.py#L311

**Comment by kallewesterling** [comment]
These have been moved to the `removed` directory, so closing this issue.
